pricelist = [
    {
        item_id: 'kensolua-14d',
        item_discount: 0,
        item_price: '70 Руб',
        item_term: '2 нед. (14д)',
        pay_link: 'https://pay.cloudtips.ru/p/d97e09bd',
    },
    {
        item_id: 'kensolua-30d',
        item_discount: 0,
        item_price: '130 Руб',
        item_term: '1 мес. (30д)',
        pay_link: 'https://pay.cloudtips.ru/p/5805d96d',
    },
    {
        item_id: 'kensolua-90d',
        item_discount: 0,
        item_price: '170 Руб',
        item_term: '3 мес. (90д)',
        pay_link: 'https://pay.cloudtips.ru/p/039e249a',
    },
    {
        item_id: 'kensolua-180d',
        item_discount: 0,
        item_price: '230 Руб',
        item_term: '6 мес. (180д)',
        pay_link: 'https://pay.cloudtips.ru/p/1a5bda74',
    },
    {
        item_id: 'kensolua-365d',
        item_discount: 0,
        item_price: '270 Руб',
        item_term: '1 год. (365д)',
        pay_link: 'https://pay.cloudtips.ru/p/034c84f9',
    },
    {   
        item_id: 'kensolua-pro',
        item_discount: 0,
        item_price: '500 Руб',
        item_term: 'Навсегда',
        pay_link: 'https://pay.cloudtips.ru/p/8c833222',
    },
    {   
        item_id: 'donate',
        item_discount: -1,
        item_price: 'Пожертвование',
        item_term: 'На развитие проекта',
        pay_link: 'https://pay.cloudtips.ru/p/c6fe8558',
    },
    {   
        item_id: 'invite',
        item_discount: 98,
        item_price: '10000 Руб',
        item_term: 'Invite код FT (Ограничено!)',
        pay_link: 'https://pay.cloudtips.ru/p/c6fe8558',
    },
]